name: sticklebacks
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - dask
  - dask-image
  - matplotlib
  - seaborn
  - scikit-image
  - imageio
  - zarr
  - jupyterlab
  - ipywidgets
  - dask-labextension
  - matplotlib-scalebar
  - k3d
  - openpyxl
  - tqdm
  - joblib
  - pip
  - pip:
    - pynrrd

